name: Inline Helper API
title: Inline Helper API
description: API minimal documentation
theme: jekyll-theme-minimal
domain: docs.inline.help       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://docs.inline.help  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /                     # place folder name if the site is served in a subfolder
markdown: kramdown
highlighter: rouge
